[package]
name = "yt-mp3"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.10"
reqwest = { version = "0.11.20", features = ["blocking"] }
regex = "1.9.5"
